### PR TITLE
add ww2a grant as blog post

### PR DESCRIPTION
**Pull request by jjfiv**
Pls review: @etosch @strubell @Shamya

### CODE REVIEW

**Comment by etosch** [comment]
lgtm

**Comment by strubell** [comment]
There's an issue with enumeration where you have three 1. s (rather than 1.
2. 3.)

I would also recommend breaking up the text of the proposal a bit, it's
currently one huge block and could really use some paragraphs.

I can make these changes sometime tomorrow if nobody else gets to it before
then.

**Comment by jjfiv** [comment]
@strubell

I swear the paragraphs render for me, and the 1.s are a markdownism. I think this is a case where we should switch back away from the submodule -- there should be an URL to preview if it were one repo.

**Comment by strubell** [comment]
oops -- ok, I was viewing in github which I thought would render properly.
In that case looks great and I think we should merge!

**Comment by Shamya** [comment]
Looks for good for me too ! Thanks John for putting it together.

**Pull request merged**
